# Generated by Django 3.2 on 2021-04-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_productinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
